### ISSUE TITLE
Version 3.0.0 release date?

### ISSUE THREAD

**Issue by alekseykulikov** [indexeddbshim/IndexedDBShim#262]
[List of changes](https://github.com/axemclion/IndexedDBShim/blob/master/CHANGES.md) is really impressive and I would like to try it! Maybe RC for testing?

**Comment by brettz9** [comment]
See pars. 3-5 of https://github.com/axemclion/IndexedDBShim/issues/259#issuecomment-248397722 . 

An RC is a good idea. For now `master` can be tested and should be working with Node too. Any help testing would indeed be most appreciated!

**Comment by brettz9** [comment]
FYI, my personal idea about a 3.0.0 release would be for the following additional items:
- [x] Report WebSQL `QUOTA_ERR` (4) as `QuotaExceededError` ~~and `TIMEOUT_ERR` (7) probably as `TransactionInactiveError` (and treat accordingly)~~ and any others as `UnknownError` (issue #27 relates)
- [x] `IDBCursor.update` should delete then insert rather than update
- [x] Event bubbling and `preventDefault` (#253)
- [x] Where possible, support `IDBTransaction.abort` rollbacks for non-upgrade transactions, browser, upgrade transactions and support automated `AbortError`  for requests with rollbacks
- [x] Add support for new getters (including #232)
- [x] Ensure cache invalidation is occurring across all `IDBObjectStore` instances
- [x] Investigate pending/deleted index/store behavior (recreation, renaming), index problems on `w3c/IDBObjectStore.createIndex.js`, and deleted status across all `IDBObjectStore` instances (#276)
- [x] Fix `IDBObjectStore` and `IDBIndex` renaming (#287)
- [ ] ~Provide optional Node support for accurate task/microtask behavior #296~ *Changed to 3.1.0 milestone.*
- [ ] ~~`close` and single and~~ multiple process support `blocked` and `versionchange` events (includes issue #2 and should be done with both issues in #273 for better performance and spec compliance of websql with read transactions) *Changed to 3.1.0 milestone.*
- [ ] ~Fix  the new W3C web-platform-tests submodule testing environment (launched from [`test-support/node-indexeddbshim-test.js`](https://github.com/axemclion/IndexedDBShim/blob/master/test-support/node-indexeddbshim-test.js) via `npm run w3c`) (the old W3C tests are mostly passing except those related to the above but barely anything is passing from the new W3C environment I set up, no doubt because of test set-up rather than that many exposed bugs) and then see if there is anything else critical that turns up; also implement for browser; Report discovered issues if not able to fix (#249)~ Also implement headlesss; *Changed to 3.1.0 milestone*
- [x] Investigate existing issues (#220, #227, #233, #260, #263, #270, #271 ? also #101, #240, #258 for other env't fixes?) ~~for critical fixes, particularly those~~ dealing with [specific browsers not working](https://github.com/axemclion/IndexedDBShim/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22Bug-environment%20support%22%20-label%3ACSP); auto-recover Safari quota problems if possible
    - [x] Investigate need for upgrading `polyfill.js`, including for newly added APIs (#277)
- [x] ~Wrap up (#264?)~ ~including getting all non-versioned dependencies put into versions for greater stability in testing~ *(We are ok on the latter account as shrinkwrapping)*

**Comment by brettz9** [comment]
As mentioned at #249 , we are really ready now for specific browser testing. While I have not gotten all of the issues resolved that I intended, I think it is good enough for a release candidate, especially if people will help get the remaining Chrome/Safari issues not present in Node passing (which should be easier now that the W3C browser testing can be run against our polyfill with single tests and, where it works like in Chrome, in bulk testing).

If this is ok with you, @axemclion , and if we hear interest in helping with W3C browser bug fixing, @alekseykulikov , etc., I think we're ready.

But bear in mind that my work was mostly geared for Node.js support; the browser should also work when the full shim is applied, but there are currently failures in the browser that do not occur in Node; those interested in getting browser support applied to the new (breaking) release ought to help out. Please also see #277 for an issue in particular need of consideration, what to do about the code rot for ~iOS9/non-Chrome Android~ IE and whether anyone can bring it up to date or whether we should remove it or what not...

**Comment by tarjei** [comment]
Thanks!

**Comment by brettz9** [comment]
~I recommend that, unless some volunteers available to carry it along (#277), we abandon iOS9 support for version 3.0.0 (which would be a breaking release anyways).~ The polyfilling was apparently for IE rather than iOS9, so the IE plugging is what is being dropped (all or nothing). Whatever value there is left in shimming the likes of modern Chrome and Safari 10, there is, I think, definite utility in getting out a Node package now (and btw, I just pushed a few more fixes to `master`, leaving us with just a handful of W3C tests that are failing or not running).

Alternatively, especially if I don't hear back from @axemclion who I guess may be too busy to even consider the issue at the moment, I might just publish a Node-supporting fork under a separate name. But if I do this, I wouldn't recommend that this current repository be reverted because there are so many fixes that if someone did want to update the polyfill to work with ~iOS9~ the browsers that used it (IE apparently), they really should start with this base, imo (and there is already the prior npm releases which can continue to be used).

Thoughts?

**Comment by brettz9** [comment]
Ok, so I've made a branch (though I plan to keep rebasing it until release) for 3.0.0. As planned, I've removed the polyfill (though it was apparently targeted instead to IE's (then?) incomplete implementation rather than iOS), so upon release, it will now be limited to all-or-nothing--polyfill everything or nothing though get Node support and better all-around compliance.

~I think I'll wait on the completion of PR #301 , but otherwise,~ I plan to publish a RC shortly, either within the current npm package if @BigstickCarpet replies to give access or in a new npm package otherwise.

**Comment by brettz9** [comment]
Ok, finally we have a release candidate--3.0.0-rc.1 is published to npm and released as a tag for Bower!

I guess I'll keep the issue open until the final release version, but I've pushed anything remaining to milestone 3.1.0.

No doubts lots that can be done, even beyond that already envisioned. Look forward to hearing how it's working for ya or if y'all end up using it in interesting ways...

**Comment by brettz9** [comment]
Sorry for the comment spam, but realized I did need to adjust the key sorting for better future-compatibility after all.. Now released as RC 2...

**Comment by brettz9** [comment]
On RC 6 now. I've updated the version 3 to-do list to take into account that the goals are either completed, or a few migrated to milestone 3.1.0.

Really hope we get some folks testing now so that our 3.0.0 release is well-tested.

**Comment by brettz9** [comment]
Ok, just pushed out `3.0.0`. Thanks to those who assisted with bug reports, etc.!
