### ISSUE TITLE
Export improvements

### ISSUE THREAD

**Issue by brettz9** [indexeddbshim/IndexedDBShim#283]
Some enhancements related to exports:

1. [ ] ~See about moving to Rollup and~ provide ES distribution for non-invasive build at least
1. [ ] We could review the exports to ensure that modules can be as independent as possible (as raised in https://github.com/dfahlander/Dexie.js/issues/359 ); we currently depend on `setGlobalVars` to do this and though it can work with a non-global, it still requires loading all modules
    1. [ ] Consider making `DOMStringList` and `DOMException` (`ShimEvent`, `ShimCustomEvent`, `ShimEventTarget` are available from a separate repository) as separate repositories and include them (though `DOMStringList` has, I believe, been removed from everything but IndexedDB anyways though it had been in use previously)
    1. [ ] Consider whether the current approach of adding to a non-standard `modules` property on `indexedDB`/`IDBFactory` can be removed in favor of an export which includes the shims and objects for test comparison (particularly in our "noninvasive" build)
    1. [ ] While not strictly concerned with exports, we might also use the review to consider removing non-standard private class and instance methods (or properties).
    1. [ ] There is one non-modular bit in `setGlobalVars` which optionally adds the slowly-performant `setPrototypeOf` if the optional `CFG.fullIDLSupport` is set. This is required for better W3C testing compliance but which probably is of not much use (so it is not on by default). If we wanted that to be done modularly, we'd need to either expect the CFG value to be already set up before the import or add methods to each module to allow setting there).
1. [ ] We have an increasingly good quality (dedicated) Worker shim which supports IndexedDB (based on `webworker`) which ought to probably be exported (and in its own repository if cyclic dependencies with this repo do not become an issue). (Compare to https://github.com/audreyt/node-webworker-threads , however?)
1. [ ] In the vein of item no. 3, we ought to add and export `SharedWorker` and `ServiceWorker` shims (at least add them for our testing) adding possibly to their own independent repositories
    1. [ ] See https://github.com/wikimedia/node-serviceworker
    1. [ ] See https://www.npmjs.com/package/shared-worker-loader
1. [ ] [jsdom integration](https://github.com/tmpvar/jsdom/issues/1748)
    1. [ ] A number of methods need to properly convert to `DOMString` (`ToString`) as opposed to using `String()` (the ones with sequence or DOMString are already fixed).
    1. [ ] Although jsdom's reliance on WebIDL may obviate the need for some of `setGlobalVars`, some might need to be (optionally) integrated (`Object.setPrototypeOf`?).
    1. [ ] `open` and `deleteDatabase` are throwing `SecurityError` `DOMException`s when attempted from an opaque origin but we can't test currently due to lack of [`iframe srcdoc` support](https://github.com/tmpvar/jsdom/issues/1792) in jsdom. See also `idbfactory-open-opaque-origin.html` and `idbfactory-deleteDatabase-opaque-origin.html`.
    1. [ ] [`ArrayBuffer.transfer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer) support or its equivalent is not available for proper `postMessage` support as used in https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/idb-binary-key-detached.htm ; see https://github.com/tmpvar/jsdom/issues/1838 . As mentioned in comments, we could also use access to `[[Detached]]` and `IsDetachedBuffer `--see #286 in regard to such better SCA support.
1. [ ] Use `es-identifiers` as modest dev dependency instead of baking in to the repo a redundant large regex

**Comment by brettz9** [comment]
Tracking this issue for new package at https://github.com/indexeddbshim/indexeddbshim/issues/14
